backend:
  name: git-gateway
  branch: main

media_folder: "assets/images" # Folder for uploaded images
public_folder: "/images"

collections:
  - name: "blog"
    label: "Blog"
    folder: "_blog"
    create: true
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "body", label: "Body", widget: "markdown" }